import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import SideBar from '../components/sidebar/SideBar'
import MainCard from '../components/maincard/MainCard'
import HistoryCard from '../components/history/HistoryCard'


export default function Home() {
  return (
    <div className={styles.maincontainer}>
      <Head>
        <title>Simple Bank</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://cdn.discordapp.com/attachments/1133070686869524531/1166040304198099084/sb-transformed-removebg-preview.png?ex=65490aa8&is=653695a8&hm=e3f98303948437e9e0977ad7e9a0e5ff325786587bb0bf90783a65596141e3a4&" />
      </Head>

      <main className="row m-0">
        <SideBar/>
        <MainCard />
        <HistoryCard />
      </main>

    
    </div>
  )
}
